### ISSUE TITLE
Posting of uploaded pictures doesn't work

### ISSUE THREAD

**Issue by the-0ther** [krokofant/JodelXposed#12]
After posting an uploaded Picture the message "jodel has no internet connection" appears. The post doesn't appear and you can't vote or post for ~10 minutes. 
Jodel version 4.12.5

**Comment by krokofant** [comment]
The underlying error is _NotSignedError_ that states that a request with an image must be signed. The thing is - the request is signed. Because this feature at least worked before the beta and our code hasn't changed I assume this has to do with the beta.

~~For a temporary solution you can install the pre-beta (stable) Jodel version and the corresponding Jodel Xposed version.~~

**Comment by doktormerlin** [comment]
The same error occurs for me now when trying to post a normal text Jodel. I haven't got a beta update though (V4.12.5 (1000018))

**Comment by krokofant** [comment]
Comment from Revolutio on XDA:

> In the unmotified jodel app the json at posting IMG/jodel has the color Tag without #.
> 
> Using this xposed module, the color has a # at the json packet.

Edit: I have not been able to reproduce this.
