### ISSUE TITLE
Make the Replace Image button more visible

### ISSUE THREAD

**Issue by krokofant** [krokofant/JodelXposed#51]
When replacing a taken image the button text "Replace Image" is dark which is almost not visible on dark images.

The button could be moved down next to the download and send button and be formatted as those buttons.

**Comment by Unbrick** [comment]
What about adding a ImageButton to the CreateTextPostFragment which calls in onClick the picture-taken-handling method in PostCreationFragment which inflates a PhotoEditFragment with a predefined bitmap?

**Comment by krokofant** [comment]
@Unbrick I don't exactly follow what this would look like. Could you elaborate on the user perspective?

Are you suggesting something like:
1. adding a button next to the _original take photo_ button
2. that triggers the Gallery Picker
3. which in turn automatically triggers the camera to shoot a photo
4. and finally replaces the taken image with the selected one?

**Comment by Unbrick** [comment]
@krokofant Yes nearly. Skipping the step with triggerting the camera and taking the picture because the picture is always handeled as a bitmap in the PostCreationFragment (Which is parent of CameraFragment and CreateTextPostFragment). So the user could directly open the gallery from the CreateTextPostFragment and would get instantly in the PhotoEditFragment, skipping the entire camera part.

**Comment by krokofant** [comment]
@Unbrick I see what you mean now. Any idea how to directly go to the PhotoEditFragment view, in a safe manner, after the image has been selected?

**Comment by Unbrick** [comment]
Closed with 947be289c85780eb5aa5ee7b8ad44407cc90d06b
Added an entirely new layout for sharing images from the gallery
